apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: homepage
        env:
        - name: ENVIRONMENT
          value: "staging"
