---
creation_rules:
    - path_regex: .*\.(enc\.yaml|cfg\.lua\.enc|conf\.enc|.sops\.yaml)$
      age: age1tg7mxj9xaa72e3pr2wvwg0w9c0drvc8anfldrzksxhsmmn3rqsnqe5rmfv
      encrypted_regex: ^(data|stringData|password|secret|token|api_key|domain)$
      partial_encryption: true
