---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prosody-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # BOSH needs WebSocket support
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
spec:
  rules:
    - host: 
        valueFrom:
          secretKeyRef:
            name: prosody-secrets
            key: domain  # The key in your secret
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prosody-service  # Replace with your Prosody service name
                port:
                  number: 5280  # The port Prosody is running on
  tls:
    - hosts:
        - 
          valueFrom:
            secretKeyRef:
              name: prosody-secrets
              key: domain  # The key in your secret
      secretName: prosody-tls
