---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: wireguard-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wireguard-repo
  policy:
    alphabetical:
      order: asc  # This will always select the highest tag (including 'latest')
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: wireguard-repo
  namespace: flux-system
spec:
  image: linuxserver/wireguard
  interval: 1h  # Check for new images hourly
