---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-networking
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/k3s/infrastructure/networking"
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
