---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-networking
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/k3s/infrastructure/networking"
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  dependsOn:
    - name: flux-system
