apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/k3s/apps/nextcloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client 