apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: '2.2.1'
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - host: nextcloud.homelab.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
       - secretName: nextcloud-tls
         hosts:
           - nextcloud.homelab.local 