apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - helm-repository.yaml
  - helm-release.yaml
secretGenerator:
  - name: nextcloud-secrets
    envs:
      - secrets.yaml
    options:
      disableNameSuffixHash: true 
