apiVersion: ENC[AES256_GCM,data:FaZoqFxC3krE7w0XRiyBK6eU,iv:J0c5tEMYgqC1DcNc2cB7P0l/ZPTBZmuLl5NF+hz/DWw=,tag:GbVeA7ZRzAjMbALRHEcpTw==,type:str]
kind: ENC[AES256_GCM,data:1IxlbB2VfwhCfQ+vqA==,iv:uGtJ3q+Rjh64684TSKzGQFN6dYLlWiPjAq4vqh2HRMU=,tag:Z3cKRBHR3kex/QLfYk3Yvw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Bm32zJ9EM9LVtkl3Ian0mQ==,iv:XvGk4weqhv8iwItXq5474n+TDHO/kJq3i4uX2GXnuWE=,tag:KKijZS+sLwpdGqmj5VQ9OA==,type:str]
spec:
    acme:
        server: ENC[AES256_GCM,data:T2JBog9ao0Rh4Iv5TGIkSNETMA4bueatlm6TPs0mGDev2DTkq3xpdZQggfVqnQ==,iv:rOgl9fejWprOeWchG2txEmPcxcX5/mia9u9nzt7SpXw=,tag:cFtqQB/iK6SU5YA55iLdzw==,type:str]
        email: ENC[AES256_GCM,data:UfQYytMZOVOmKkK6Fo07vSUlgHeDDznsyY5iMgA=,iv:rhJWsh2ZUjU1/+3S7qhL8dmybrWeRZnq6zVOwyLGoVY=,tag:3STcPemZd8W13kGDQVI0kg==,type:str]
        privateKeySecretRef:
            #ENC[AES256_GCM,data:AwBwcUSi3hxj0/8oITSKJU/WqRznvZ5T2itbD6HpJCc=,iv:3F5MsT5CUN3md5C2FjmEgFc6bBlMlXoPEjSELQLB3lE=,tag:DBArYCUDGdsIsRMgY7WHbg==,type:comment]
            name: ENC[AES256_GCM,data:5I6vZlvDva1r3s/y9rLtZXLHBZw=,iv:nGHvZhq4hVdj8EBwqaozQYhEac1BJjevuOsr+FBjCwU=,tag:I2aX6fvx8cwUQoAW5w//GQ==,type:str]
        solvers:
            - http01:
                ingress:
                    #ENC[AES256_GCM,data:pWpYO71yWySkGcK5bJeBuu3H1YDk8np6CDsHt+O0pKE+iQ2EbPiC5Wi1HihYjjtAsiaUQtylEuxRA9zv+nJtQPB5jyM=,iv:PFjUFaPJDounuKKwaRAZ1pveUlDRooibfcdm5dSi/g0=,tag:CYSzYAb/PZ+3iEdZ1ndQBw==,type:comment]
                    class: ENC[AES256_GCM,data:H1zR7Go=,iv:/uf3sAr4bFuwBk8JmBUElys9QyrXXC8uVlx7Vas81AY=,tag:P0O5+n5R2lluXrWLN6piRA==,type:str]
sops:
    age:
        - recipient: age1tg7mxj9xaa72e3pr2wvwg0w9c0drvc8anfldrzksxhsmmn3rqsnqe5rmfv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS0RocTlPS2drV21PeUVB
            ZGlZb2pWeWNBd2tIZlg3ZDhpTXRZWXBsSVdRCnVrZENPTWh6aDJVRlFxdjZibkdw
            WDNtaXp3SytKUVRaRGZpOXdoVy9ya0kKLS0tIE5nZUp3eDFHbWtCdVZacU1pcFVG
            bGd5REdRdURuUGxpUGFDY2s4RXJQRGMKq2SN1EzCamR7WCsHGWZBfJUALN49yJfn
            hKm/SQEUU2nATek7g3vNqXzq0coduOybK8IanfvDQAU8RStrsx/i2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-05T07:50:16Z"
    mac: ENC[AES256_GCM,data:kn6F7zHP+gh0M/iiJLnLgWxPLQiHEO7Pfw72Y8BEVYjpj0rs2Jhe8OSX/7yUydTTCo9taYtp7VASS2DsMGtgDWsma2LHv7or8997T5/LtkuTZ3EbemU6nmU4gnLpzepO2XPXNNUkYKPs8Vp1GaAlt4fK3tcgWhEZC1TXoSQOxTE=,iv:lmsjOKNOBcBAzihEBMWvw56hGWRpKDTnJDrEAIjS8Q0=,tag:hzNe5vdcLfn/0kWT6evOIw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.0
