---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
          image: lscr.io/linuxserver/wireguard:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Athens"
          volumeMounts:
            - name: config
              mountPath: /config
          ports:
            - containerPort: 51820
              protocol: UDP
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
      volumes:
        - name: config
          secret:
            secretName: wireguard-config
      hostNetwork: true  # Required for UDP port binding
