---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - deployment.yaml
  - service.yaml
secretGenerator:
  - name: wireguard-config
    files:
      - wg0.conf=wg0.conf.enc
    options:
      disableNameSuffixHash: true
