---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - deployment.yaml
  - rbac.yaml
  - service.yaml
images:
  - name: linuxserver/wireguard
    newName: linuxserver/wireguard
    newTag: latest  # Will be maintained by Flux
secretGenerator:
  - name: wireguard-config
    files:
      - wg0.conf=wg0.conf.enc
    options:
      disableNameSuffixHash: true
