---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wireguard
  namespace: networking
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wireguard
  namespace: networking
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wireguard
  namespace: networking
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wireguard
subjects:
- kind: ServiceAccount
  name: wireguard
  namespace: networking
