---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: vpn
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
    - name: wg-udp
      port: 51820
      targetPort: 51820
      protocol: UDP
      nodePort: 31821
  selector:
    app: wireguard
