---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: networking
spec:
  type: NodePort
  ports:
    - name: wg-udp
      port: 51820
      targetPort: 51820
      protocol: UDP
      nodePort: 31820
  selector:
    app: wireguard
