---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
  namespace: xmpp
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prosody
  template:
    metadata:
      labels:
        app: prosody
    spec:
      serviceAccountName: prosody
      securityContext:  # Add this security context for the pod
        fsGroup: 1000  # Use an appropriate group ID
      containers:
        - name: prosody
          image: prosody/prosody:latest
          imagePullPolicy: Always
          securityContext:  # Add this security context for the container
            privileged: true  # Or use more specific capabilities instead
          ports:
            - containerPort: 5222
          volumeMounts:
            - name: prosody-certs
              mountPath: /etc/prosody/certs
            - name: prosody-config
              mountPath: /etc/prosody/prosody.cfg.lua
              subPath: prosody.cfg.lua
            - name: prosody-data
              mountPath: /var/lib/prosody
            - name: prosody-logs
              mountPath: /var/log/prosody
            - name: pid-dir
              mountPath: /var/run/prosody
      volumes:
        - name: prosody-certs
          secret:
            secretName: prosody-certs
            optional: false
        - name: prosody-config
          secret:
            secretName: prosody-config
            optional: false  # Ensure pod fails if secret missing
        - name: prosody-data
          persistentVolumeClaim:
            claimName: prosody-data
        - name: prosody-logs
          emptyDir: {}
        - name: pid-dir
          emptyDir: {}
