---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
  namespace: networking
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prosody
  template:
    metadata:
      labels:
        app: prosody
    spec:
      serviceAccountName: prosody
      containers:
        - name: prosody
          image: prosody/prosody:latest
          imagePullPolicy: Always  # Force pull new image on update
          ports:
            - containerPort: 5222  # Client connections
            - containerPort: 5269  # Server-to-server
            - containerPort: 5280  # HTTP for BOSH
          volumeMounts:
            - name: prosody-certs
              mountPath: /etc/prosody/certs
            - name: prosody-config
              mountPath: /etc/prosody/prosody.cfg.lua
              subPath: prosody.cfg.lua
      volumes:
        - name: prosody-certs
          secret:
            secretName: prosody-certs
            optional: false  # Ensure pod fails if secret missing
        - name: prosody-config
          secret:
            secretName: prosody-config
            optional: false  # Ensure pod fails if secret missing
