---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
  namespace: networking
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prosody
  template:
    metadata:
      labels:
        app: prosody
    spec:
      serviceAccountName: prosody
      containers:
        - name: prosody
          image: prosody/prosody:latest
          imagePullPolicy: Always  # Force pull new image on update
          ports:
            - containerport: 5222  # client connections
            - containerport: 5269  # server-to-server
            - containerport: 5280  # http for bosh
          volumemounts:
            - name: prosody-certs
              mountpath: /etc/prosody/certs
            - name: prosody-config
              mountpath: /etc/prosody/prosody.cfg.lua
              subpath: prosody.cfg.lua
            - name: pid-dir
              mountPath: /var/run/prosody
      volumes:
        - name: prosody-certs
          secret:
            secretName: prosody-certs
            optional: false  # Ensure pod fails if secret missing
        - name: prosody-config
          secret:
            secretName: prosody-config
            optional: false  # Ensure pod fails if secret missing
        - name: pid-dir
          emptyDir: {}
