---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - deployment.yaml
  - rbac.yaml
  - service.yaml
images:
  - name: prosody/prosody
    newName: prosody/prosody
    newTag: latest
secretGenerator:
  - name: prosody-certs
    files:
      - tls.key=tls.key.enc
      - tls.crt=tls.crt.enc 
    options:
      disableNameSuffixHash: true
  - name: prosody-config
    files:
      - prosody.cfg.lua=prosody.cfg.lua.enc
    options:
      disableNameSuffixHash: true
