---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prosody
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - pvc.yaml
images:
  - name: prosody/prosody
    newName: prosody/prosody
    newTag: latest  # Will be maintained by Flux
secretGenerator:
  - name: prosody-config
    files:
      - prosody.cfg.lua=prosody.cfg.lua.enc
    options:
      disableNameSuffixHash: true
