---
apiVersion: v1
kind: Service
metadata:
  name: prosody
  namespace: networking
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
    - name: xmpp
      port: 5222
      targetPort: 5222
      protocol: TCP
      nodePort: 30522
    - name: bosh
      port: 5280
      targetPort: 5280
      nodePort: 30580
  selector:
    app: prosody
