---
apiVersion: v1
kind: Service
metadata:
  name: prosody
  namespace: xmpp
spec:
  type: NodePort
  ports:
    - name: client
      port: 5222
      targetPort: 5222
      protocol: TCP
      nodePort: 31222
    - name: proxy65
      port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30500
  selector:
    app: prosody
