---
apiVersion: v1
kind: Service
metadata:
  name: prosody
  namespace: networking
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
    - name: xmpp-tcp
      port: 5222
      targetPort: 5222
      protocol: TCP
      nodePort: 30522
  selector:
    app: prosody
