---
apiVersion: v1
kind: Service
metadata:
  name: prosody
  namespace: networking
spec:
  type: ClusterIP
  ports:
    - name: xmpp-c2s
      port: 5222
      targetPort: 5222
      protocol: TCP
    - name: xmpp-s2s
      port: 5269
      targetPort: 5269
      protocol: TCP
    - name: http
      port: 5280
      targetPort: 5280
      protocol: TCP
    - name: https
      port: 5281
      targetPort: 5281
      protocol: TCP
  selector:
    app: prosody
      
---
# If you need to expose XMPP ports directly, create a NodePort or LoadBalancer service
apiVersion: v1
kind: Service
metadata:
  name: prosody-xmpp
  namespace: networking
spec:
  type: NodePort  # Or LoadBalancer if available
  ports:
    - name: xmpp-c2s
      port: 5222
      targetPort: 5222
      protocol: TCP
      nodePort: 30222
    - name: xmpp-s2s
      port: 5269
      targetPort: 5269
      protocol: TCP
      nodePort: 30269
  selector:
    app: prosody
